//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PC_02_Module3
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_order
    {
        public int id { get; set; }
        public int header_order_id { get; set; }
        public int menu_id { get; set; }
        public decimal order_price { get; set; }
        public int quantity { get; set; }
        public System.DateTime order_placed_time { get; set; }
    
        public virtual header_order header_order { get; set; }
        public virtual menu menu { get; set; }
    }
}
