//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PC_02_Module3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PC_02_Module3Entities : DbContext
    {
        public DB_PC_02_Module3Entities()
            : base("name=DB_PC_02_Module3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detail_order> detail_order { get; set; }
        public virtual DbSet<header_order> header_order { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<menu_category> menu_category { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
    }
}
